param([Parameter(Mandatory=$true)][string]$BundleRoot)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Root=Join-Path $env:LOCALAPPDATA 'FleshpunkCauldron';$StateDir=Join-Path $Root 'state';$Lock=Join-Path $StateDir 'overnight.lock';$LogDir=Join-Path $Root 'logs';$Out=Join-Path $Root 'models\loras';$Dataset=Join-Path $Root 'dataset\p0-lineart';$Selected=Join-Path $BundleRoot 'selected';$Acceptance=Join-Path $BundleRoot 'user-acceptance.json';$ProjectionReceipt=Join-Path $BundleRoot 'preprocess-receipt.json';$Base=Join-Path $Root 'models\checkpoints\v1-5-pruned-emaonly.safetensors';$BaseHash='6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa';$BaseUrl='https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors';$V1Hash='a064beabd85ad3710ad51a5fdd6934e69ac5b714bc9ab953f5d3472ac6ab6d90';$V1=Join-Path $Out 'drw_fleshpunk_v1.safetensors';$V2=Join-Path $Out 'drw_fleshpunk_maze_line_v2.safetensors';$Sd=Join-Path $Root 'source\sd-scripts';$Comfy=Join-Path $Root 'source\ComfyUI';$WorkspaceRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$Review=Join-Path $PSScriptRoot 'review_campaign.py';$Catalog=Join-Path $WorkspaceRoot 'data\fleshpunk_asset_targets.json';$BoxCli=Join-Path $WorkspaceRoot 'tools\boxcraft-judgment-mcp\src\asset-review-cli.mjs';$Trace=Join-Path $Selected 'fp_pressure_valve_gate_line_v3.png';$ReviewOut=Join-Path $Root 'reviews\latest';$Py='py';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
New-Item -ItemType Directory -Force -Path $StateDir,$LogDir,$Out,(Split-Path $Base) | Out-Null
function State([string]$stage,[string]$status,[string]$detail=''){ $x=[ordered]@{schema='FLESHPUNK OVERNIGHT STATE 1';run_id=$RunId;updated=(Get-Date).ToUniversalTime().ToString('o');pid=$PID;stage=$stage;status=$status;detail=$detail;finalAcceptance='USER_ONLY'};$tmp=Join-Path $StateDir 'latest.json.tmp';$x|ConvertTo-Json -Depth 6|Set-Content $tmp -Encoding utf8;Move-Item $tmp (Join-Path $StateDir 'latest.json') -Force }
if(Test-Path $Lock){$Owner=Join-Path $Lock 'owner.json';if(-not(Test-Path $Owner)){State 'lock' 'OBSERVE' 'ambiguous lock without owner receipt';exit 0};$old=Get-Content $Owner -Raw|ConvertFrom-Json;if(-not $old.pid){State 'lock' 'OBSERVE' 'ambiguous lock owner without pid';exit 0};$alive=Get-Process -Id $old.pid -ErrorAction SilentlyContinue;if($alive){State 'lock' 'OBSERVE' "active pid $($old.pid)";exit 0};Remove-Item $Lock -Recurse -Force}
New-Item -ItemType Directory $Lock|Out-Null;[ordered]@{pid=$PID;run_id=$RunId}|ConvertTo-Json|Set-Content (Join-Path $Lock 'owner.json') -Encoding utf8
try{
 State 'dataset' 'RUNNING'
 if(-not(Test-Path $Selected)){throw 'selected lineart projection missing'}
 New-Item -ItemType Directory -Force -Path $Dataset|Out-Null
 Get-ChildItem $Dataset -File -ErrorAction SilentlyContinue|Remove-Item -Force
 Get-ChildItem $Selected -File|Where-Object{$_.Extension -in '.png','.txt'}|ForEach-Object{Copy-Item $_.FullName (Join-Path $Dataset $_.Name) -Force}
 if((Get-ChildItem $Dataset -Filter '*.png').Count -ne 9 -or (Get-ChildItem $Dataset -Filter '*.txt').Count -ne 9){throw 'dataset requires exactly nine selected PNG and caption pairs'}
 if(-not(Test-Path $Acceptance) -or -not(Test-Path $ProjectionReceipt)){State 'pixel_gate' 'OBSERVE' 'missing acceptance or projection receipt';exit 0}
 $Accepted=Get-Content $Acceptance -Raw|ConvertFrom-Json;$Projection=Get-Content $ProjectionReceipt -Raw|ConvertFrom-Json
 if($Accepted.schema -ne 'FLESHPUNK PIXEL ACCEPTANCE 1' -or $Accepted.accepted -ne $true -or $Accepted.accepted_by -ne 'USER'){State 'pixel_gate' 'OBSERVE' 'selected pixels await explicit USER acceptance';exit 0}
 if($Accepted.selected_images -ne 9 -or $Accepted.selected_pixel_aggregate_sha256 -ne $Projection.selected_pixel_aggregate_sha256){State 'pixel_gate' 'OBSERVE' 'stale or partial user acceptance receipt';exit 0}
 State 'source' 'RUNNING'
 if(-not(Test-Path $Sd)){git clone --filter=blob:none https://github.com/kohya-ss/sd-scripts.git $Sd|Out-Null};git -C $Sd fetch origin 37a1cbbc5725ed2a3575506e7bd2001c9908ac92|Out-Null;git -C $Sd checkout --detach 37a1cbbc5725ed2a3575506e7bd2001c9908ac92|Out-Null
 if(-not(Test-Path $Comfy)){git clone --filter=blob:none https://github.com/Comfy-Org/ComfyUI.git $Comfy|Out-Null};git -C $Comfy fetch origin 250b2e9551a7bc7a8ebb5beb07e0fecd2983e04a|Out-Null;git -C $Comfy checkout --detach 250b2e9551a7bc7a8ebb5beb07e0fecd2983e04a|Out-Null
 $Venv=Join-Path $Root 'venvs\sd-scripts';if(-not(Test-Path (Join-Path $Venv 'Scripts\python.exe'))){& $Py -3.12 -m venv $Venv};$Python=Join-Path $Venv 'Scripts\python.exe';$Pip=Join-Path $Venv 'Scripts\pip.exe'
 $Ready=Join-Path $Venv '.fleshpunk-ready';if(-not(Test-Path $Ready)){State 'dependencies' 'RUNNING';& $Python -m pip install --disable-pip-version-check -U pip;& $Pip install --disable-pip-version-check torch torchvision --index-url https://download.pytorch.org/whl/cu128;& $Pip install --disable-pip-version-check -r (Join-Path $Sd 'requirements.txt');'ready'|Set-Content $Ready}
 $ComfyVenv=Join-Path $Root 'venvs\comfy';if(-not(Test-Path (Join-Path $ComfyVenv 'Scripts\python.exe'))){& $Py -3.12 -m venv $ComfyVenv};$ComfyPython=Join-Path $ComfyVenv 'Scripts\python.exe';$ComfyReady=Join-Path $ComfyVenv '.fleshpunk-ready'
 if(-not(Test-Path $ComfyReady)){State 'comfy_dependencies' 'RUNNING';& $ComfyPython -m pip install --disable-pip-version-check -U pip;& $ComfyPython -m pip install --disable-pip-version-check torch torchvision --index-url https://download.pytorch.org/whl/cu128;& $ComfyPython -m pip install --disable-pip-version-check -r (Join-Path $Comfy 'requirements.txt');& $ComfyPython -c "from torchvision.models import RegNet_X_400MF_Weights; RegNet_X_400MF_Weights.IMAGENET1K_V2.get_state_dict(progress=True)";'ready'|Set-Content $ComfyReady}
 if(-not(Test-Path $Base) -or (Get-FileHash $Base -Algorithm SHA256).Hash.ToLowerInvariant() -ne $BaseHash){State 'base_model' 'RUNNING';& curl.exe -L --fail --silent --show-error --retry 5 --continue-at - --output $Base $BaseUrl;if($LASTEXITCODE -ne 0){throw "base download curl exit $LASTEXITCODE"}}
 if((Get-FileHash $Base -Algorithm SHA256).Hash.ToLowerInvariant() -ne $BaseHash){throw 'base model hash mismatch'}
 if(-not(Test-Path $V1) -or (Get-FileHash $V1 -Algorithm SHA256).Hash.ToLowerInvariant() -ne $V1Hash){throw 'permitted v1 LoRA missing or hash mismatch'}
 $Toml=Join-Path $Root 'dataset\p0.toml';$TomlLines=@('[general]','caption_extension = ".txt"','shuffle_caption = true','keep_tokens = 1','[[datasets]]','resolution = 512','batch_size = 1','enable_bucket = true','min_bucket_reso = 256','max_bucket_reso = 768','bucket_reso_steps = 64','  [[datasets.subsets]]',('  image_dir = "'+$Dataset.Replace('\','/')+'"'),'  num_repeats = 12');$TomlLines|Set-Content $Toml -Encoding ascii
 if(-not(Test-Path $V2)){State 'training' 'RUNNING';$args=@((Join-Path $Sd 'train_network.py'),"--pretrained_model_name_or_path=$Base","--dataset_config=$Toml","--output_dir=$Out",'--output_name=drw_fleshpunk_maze_line_v2','--network_module=networks.lora','--network_dim=8','--network_alpha=4','--network_args','conv_dim=4','conv_alpha=2',"--network_weights=$V1",'--learning_rate=0.0001','--unet_lr=0.0001','--text_encoder_lr=0.00005','--max_train_steps=600','--save_every_n_steps=150','--save_model_as=safetensors','--mixed_precision=fp16','--save_precision=fp16','--optimizer_type=AdamW8bit','--cache_latents','--sdpa','--gradient_checkpointing','--max_data_loader_n_workers=0','--persistent_data_loader_workers','--seed=314159');& $Python @args *>> (Join-Path $LogDir "train-$RunId.log");if($LASTEXITCODE -ne 0){throw "training exit $LASTEXITCODE"}}
 if(-not(Test-Path $V2)){throw 'training completed without final v2 LoRA'}
 State 'training' 'PROCEED' ((Get-FileHash $V2 -Algorithm SHA256).Hash.ToLowerInvariant())
 State 'review' 'RUNNING' 'starting fixed-seed trace recreation mutation review'
 $Paths=Join-Path $Root 'extra_model_paths.yaml';@('fleshpunk:','  base_path: '+$Root.Replace('\','/'),'  checkpoints: models/checkpoints','  loras: models/loras')|Set-Content $Paths -Encoding ascii
 $StartedComfy=$null
 try{
  try{Invoke-WebRequest 'http://127.0.0.1:8188/system_stats' -UseBasicParsing -TimeoutSec 2|Out-Null;$ComfyReadyNow=$true}catch{$ComfyReadyNow=$false}
  if(-not $ComfyReadyNow){$StartedComfy=Start-Process -FilePath $ComfyPython -ArgumentList @((Join-Path $Comfy 'main.py'),'--listen','127.0.0.1','--port','8188','--disable-auto-launch','--extra-model-paths-config',$Paths) -WorkingDirectory $Comfy -PassThru -WindowStyle Hidden}
  for($i=0;$i -lt 120;$i++){try{Invoke-WebRequest 'http://127.0.0.1:8188/system_stats' -UseBasicParsing -TimeoutSec 2|Out-Null;$ComfyReadyNow=$true;break}catch{Start-Sleep -Seconds 2}}
  if(-not $ComfyReadyNow){throw 'Comfy API did not become ready'}
  New-Item -ItemType Directory -Force -Path $ReviewOut|Out-Null
  & $ComfyPython $Review --catalog $Catalog --trace $Trace --checkpoint (Split-Path $Base -Leaf) --lora (Split-Path $V2 -Leaf) --comfy-output (Join-Path $Comfy 'output') --out $ReviewOut --boxcraft-cli $BoxCli
  if($LASTEXITCODE -ne 0){throw "review campaign exit $LASTEXITCODE"}
  $Decision=Get-Content (Join-Path $ReviewOut 'mutation-decision.json') -Raw|ConvertFrom-Json
  if($Decision.mutationDecision -eq 'APPROVE_INTERNAL'){State 'review' 'OBSERVE' 'RegNet and Boxcraft approve internal mutation; final acceptance USER_ONLY'}else{State 'review' 'REJECT' ("mutation decision: "+$Decision.mutationDecision)}
 } finally {if($StartedComfy -and -not $StartedComfy.HasExited){Stop-Process -Id $StartedComfy.Id -Force}}
} catch { State 'failed' 'REJECT' $_.Exception.Message;throw } finally { if(Test-Path $Lock){Remove-Item $Lock -Recurse -Force} }
