import assert from 'node:assert/strict';
import fs from 'node:fs';

const mainSource = fs.readFileSync(new URL('../src/main.js', import.meta.url), 'utf8');
const districtSource = fs.readFileSync(new URL('../src/district-geometry.js', import.meta.url), 'utf8');
const terrainLayerSource = fs.readFileSync(new URL('../src/terrain-layer.js', import.meta.url), 'utf8');
const physicsSource = fs.readFileSync(new URL('../src/physics-world.js', import.meta.url), 'utf8');

assert.match(mainSource, /import \{ createTerrainLayer \} from '\.\/terrain-layer\.js/, 'main runtime must import TerrainLayer');
assert.match(mainSource, /import \{ createPhysicsWorld, ensurePhysicsReady \} from '\.\/physics-world\.js/, 'main runtime must import the Rapier physics adapter');
assert.match(mainSource, /await ensurePhysicsReady\(\)/, 'main runtime must initialize Rapier before building the room');
assert.match(mainSource, /roomState\.physicsWorld = createPhysicsWorld/, 'roomState must own the active physics world');
assert.match(mainSource, /function rapierPlayerCollisionActive\(\)/, 'runtime must expose a single switch for Rapier player collision authority');
assert.match(mainSource, /function collisionTruthSnapshot\(\)/, 'runtime must expose collision truth diagnostics');
assert.match(mainSource, /window\.__ibCollisionTruth = truth/, 'browser QA must be able to inspect collision truth from the page');
assert.match(mainSource, /ownerlessColliderCount/, 'visual QA must expose ownerless collider counts');
assert.match(mainSource, /legacySolidPlayerBlockersActive/, 'visual QA must expose whether legacy solid blockers are active');
assert.match(mainSource, /physicsStructureColliderCount/, 'visual QA must expose structure collider counts, not only terrain physics');
assert.match(mainSource, /frameMs/, 'visual QA must expose real frame time for local slowdown reports');
assert.match(mainSource, /registerPrimitivePhysicsBox/, 'visible structural primitives must have a physics registration path');
assert.match(mainSource, /kind: 'walkable'/, 'walkable architecture must register as physics walkable colliders');
assert.match(mainSource, /registerPrimitivePhysicsBox\(name, size, pos, physicsOptions\)/, 'addWalkableBox must register visible walkable architecture with Rapier');
assert.match(mainSource, /function addWallBox[\s\S]*?if \(ISLAND_ART_ONLY\) \{\n    return null;\n  \}[\s\S]*?registerSolid\(size, pos, 0\.02, \{ source: name, kind: 'structure' \}\);/, 'invisible island-art wall helpers must return before registering sourced physics walls');
const routeRailsStart = mainSource.indexOf('function addBrokenRouteRails');
const routeRailsEnd = mainSource.indexOf('function addBatchRouteSegment', routeRailsStart);
assert.ok(routeRailsStart > -1 && routeRailsEnd > routeRailsStart, 'broken route rail helper must remain inspectable');
const routeRailsSource = mainSource.slice(routeRailsStart, routeRailsEnd);
assert.doesNotMatch(routeRailsSource, /registerSolid\(/, 'broken route rails are visual edge signposting and must not block walking');
assert.doesNotMatch(routeRailsSource, /registerWalkable\(/, 'broken route rails must not add fake walkable strips on top of the route');
assert.match(mainSource, /function registerWalkable\(size, pos, margin = 0\.12, options = \{\}\) \{\n  if \(rapierPlayerCollisionActive\(\)\) return;/, 'legacy walkable support must not populate while Rapier owns player collision');
assert.match(mainSource, /if \(!rapierPlayerCollisionActive\(\)\) \{\n    solidColliders\.push\(/, 'legacy solid blockers must not populate while Rapier owns player collision');
assert.match(mainSource, /function registerMeshSupportCollider\(object, options = \{\}\) \{\n  if \(rapierPlayerCollisionActive\(\)\) return null;/, 'legacy mesh support colliders must not populate while Rapier owns player collision');
assert.match(mainSource, /function registerVoxelSupportCollider\(field, options = \{\}\) \{\n  if \(rapierPlayerCollisionActive\(\)\) return null;/, 'legacy voxel support colliders must not populate while Rapier owns player collision');
assert.match(mainSource, /if \(!options\.force\) return;/, 'primitive physics boxes must be explicit, not promoted by source-name heuristics');
assert.doesNotMatch(mainSource, /const decorative = .*crossbar/, 'primitive physics registration must not rely on decorative name heuristics');
assert.match(mainSource, /roomState\.terrainLayer = layer/, 'roomState must own the active TerrainLayer');
assert.match(mainSource, /roomGroup\.add\(layer\.group\)/, 'TerrainLayer group must be attached as one terrain owner');
assert.doesNotMatch(mainSource, /addIslandArtSteppedRamp\('slice-ramp-/, 'active island-art connectors must not emit floating terrain ramp spans');
assert.match(districtSource, /activeTerrainLayer/, 'district geometry must target active TerrainLayer');
assert.match(districtSource, /terrain\.addIslandStamp\(/, 'district islands must be terrain layer stamps');
assert.match(districtSource, /terrainMode === 'carved_imperial_structure'/, 'district geometry must have a carved structure path before island bridge fallback');
assert.doesNotMatch(districtSource, /road-crossbar/, 'upper terrace route markings must not draw full-width crossbars across walkable lanes');
assert.match(districtSource, /road-edge-tick/, 'upper terrace route markings should stay on the route edges');
assert.doesNotMatch(districtSource, /registerMeshSupportCollider\(/, 'district terrain must not register mesh support colliders directly');
assert.doesNotMatch(districtSource, /registerVoxelSupportCollider\(/, 'district terrain must not register voxel support colliders directly');
assert.match(terrainLayerSource, /export function createTerrainLayer/, 'terrain-layer module must expose one layer factory');
assert.match(terrainLayerSource, /group\.userData\.owner = 'TerrainLayer'/, 'terrain group must declare TerrainLayer ownership');
assert.match(terrainLayerSource, /const colliders = \[\]/, 'TerrainLayer must own support colliders internally');
assert.match(terrainLayerSource, /const visualMeshes = \[\]/, 'TerrainLayer must own visual meshes internally');
assert.match(terrainLayerSource, /const meshColliders = \[\]/, 'TerrainLayer must own visible mesh colliders internally');
assert.match(terrainLayerSource, /imperial_floating_strata/, 'TerrainLayer must preserve the Imperial Floating Strata terrain label');
assert.match(terrainLayerSource, /carved_imperial_structure/, 'TerrainLayer must preserve the carved imperial structure terrain label');
assert.match(terrainLayerSource, /fieldGrammar: 'carved_imperial_structure'/, 'carved imperial structure must route to its own field builder');
assert.match(terrainLayerSource, /baseGrammar/, 'TerrainLayer must record the base field grammar when a terrain label aliases an existing generator');
assert.match(terrainLayerSource, /imperialFunction/, 'TerrainLayer must carry district function metadata into terrain fields');
assert.match(terrainLayerSource, /const addIslandStamp = /, 'TerrainLayer must own island stamp emission');
assert.match(terrainLayerSource, /const addBridgeSpan = /, 'TerrainLayer must own connector span emission');
assert.match(terrainLayerSource, /const supportAt = /, 'TerrainLayer must answer support queries');
assert.match(terrainLayerSource, /terrainSupportRaycaster\.intersectObject\(collider\.mesh, true\)/, 'TerrainLayer support must raycast against the visible terrain mesh');
assert.doesNotMatch(terrainLayerSource, /queryVoxelTopY/, 'TerrainLayer support must not sample hidden voxel tops');
assert.match(mainSource, /physicsWorld: roomState\.physicsWorld/, 'TerrainLayer must receive the room physics world');
assert.match(terrainLayerSource, /physicsWorld\?\.addTerrainMesh\?\.\(\{ meshData, origin, yaw, source, kind \}\)/, 'TerrainLayer must register generated mesh data with physics once');
assert.doesNotMatch(terrainLayerSource, /const intersectsBody = /, 'TerrainLayer must not expose custom per-frame terrain body collision');
assert.doesNotMatch(terrainLayerSource, /queryVoxelIntersectsPrism/, 'TerrainLayer body checks must not use hidden voxel occupancy');
assert.doesNotMatch(terrainLayerSource, /buildMeshWallTriangles|wallTriangles|triangleIntersectsBodyColumn/, 'TerrainLayer must not hand-roll mesh triangle body collision');
assert.match(physicsSource, /from '\.\.\/vendor\/rapier3d\/rapier\.mjs'/, 'physics adapter must use vendored Rapier, not a runtime CDN');
assert.match(physicsSource, /createCharacterController/, 'physics adapter must use Rapier kinematic character controller for player movement');
assert.match(physicsSource, /ColliderDesc\.trimesh/, 'physics adapter must support static terrain mesh colliders');
assert.match(physicsSource, /colliderRecords/, 'physics adapter must retain collider records for runtime collision truth diagnostics');
assert.match(physicsSource, /ownerlessColliderCount/, 'physics adapter snapshot must expose ownerless colliders');
assert.match(physicsSource, /terrainMeshColliderCount/, 'physics adapter snapshot must expose terrain mesh collider counts');
assert.match(physicsSource, /cuboidColliderCount/, 'physics adapter snapshot must expose primitive cuboid collider counts');
assert.match(terrainLayerSource, /colliderBySource/, 'TerrainLayer must index colliders by source for spawn selection');
assert.match(terrainLayerSource, /colliders\.includes\(collider\)/, 'TerrainLayer local transforms must reject legacy colliders it does not own');
assert.match(terrainLayerSource, /disposeObjectTree/, 'TerrainLayer must own disposal for generated terrain meshes');

console.log(JSON.stringify({ ok: true, contract: 'terrain-layer-architecture' }));
